---
galaxy_info:
  role_name: podba_rac_db_install
  author: Naved Afroz
  description: This role is to Install Oracle 19c RDBMS Home on RAC nodes.
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
