# Create/Drop database variables section
oracle_user: oracle             # Provide the username who owns the Oracle Installations.
oracle_group: oinstall    	# Primary group for oracle_user.
oracle_stage: /tmp 		# Provide path on the target AIX lpar to stage response files.
oracle_base: /u01/app/oracle
oracle_dbf_dir_fs: /u01/oradata                   # Provide path on the Lpar to store datafiles.
oracle_reco_dir_fs: /u01/oradata                  # Provide path on the Lpar to store Flash recovery area files.
oracle_dbf_dir_asm: '+DATA1'                      # Provide ASM diskgroup name to store datafiles.
oracle_reco_dir_asm: '+DATA1'                     # Provide ASM diskgroup name to store Flash recovery area files.

# This is an example layout to create a database.
oracle_databases:                                     # Dictionary describing the databases to be installed.
      - home: db1                                     # 'Last' directory in ORACLE_HOME path (e.g /u01/app/oracle/db1)
        oracle_version_db: 19.3.0.0                   # Oracle version. Ex:For 12cR1 - 12.1.0.2, for 19c - 19.3.0.0
        oracle_home: /u01/db19c_2               # Oracle Home path.
        oracle_edition: EE                            # The edition of database-server (EE,SE,SEONE)
        oracle_db_name: testdb                         # Provide Database name.
        oracle_db_type: SI                           # Type of database (RAC,RACONENODE,SI)
        is_container: True                            # (true/false) Is the database a container database
        pdb_prefix: testpdb                            # Provide Pluggable database name.
        num_pdbs: 1                                   # Number of pluggable databases.
        storage_type: ASM                              # Database storage to be used. ASM or FS. ASM mandatory for RAC DB type.
        service_name: testdb                           # Inital service to be created.
        oracle_init_params: "sga_max_size=10g,sga_target=10g" # initialization parameters comma separated. Ex: sga_max_size=10g,sga_target=10g,db_recovery_file_dest_size=5g
        oracle_db_mem_totalmb: 15000                  # Amount of RAM to be used for SGA + PGA
        oracle_database_type: MULTIPURPOSE            # MULTIPURPOSE|DATA_WAREHOUSING|OLTP
        redolog_size_in_mb: 50                        # Redolog size in MB
        state: present
