- name: Create DBMS Job Window
  oracle_jobwindow:
    hostname: "{{ hostname }}"
    service_name: "{{ service_name }}"
    port: "{{ listener_port }}"
    user: "{{ db_user }}"
    password: "{{ db_password_cdb }}"
    mode: "{{ db_mode }}"
    state: "{{ state }}"
    resource_plan: "{{ resource_plan }}"
    name: "{{ window_name }}"
    interval: "{{ interval }}"
    comments: "{{ comments }}"
    duration_hour: "{{ duration_hour }}"
  environment: "{{ oracle_env }}"
  register: jobclass
- debug:
    var: jobclass
