---
galaxy_info:
  role_name: manage_acfs
  description: Ansible role to create/drop ACFS
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
