---
galaxy_info:
  role_name: podba_asm_drop_disk_dg
  description: Ansible role to drop ASM DG/Disk
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
