---
galaxy_info:
  role_name: drop_asmdg_disk_aix
  description: Ansible role to drop ASM DG
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
