- name: ASMCA | Creating script to add asm disk(s)
  ansible.builtin.template: src=asmca-diskadd-aix.sh.j2 dest="{{ oracle_rsp_stage }}/asmca-diskadd-{{ item.diskgroup }}.sh" owner="{{ grid_install_user }}" group={{ oracle_group }} mode=744 backup=no
  with_items: "{{ asm_diskgroups }}"
  when: asm_diskgroups is defined

- name: ASMCA | Add ASM disks
  ansible.builtin.shell: "{{ oracle_rsp_stage }}/asmca-diskadd-{{ item.diskgroup }}.sh"
  with_items: "{{ asm_diskgroups }}"
  become: yes
  become_user: "{{ grid_install_user }}"
  when: asm_diskgroups is defined
  ignore_errors: True

- name: Add disk status
  ansible.builtin.shell: echo "select name,PATH,STATE,HEADER_STATUS from v\$asm_disk where path='{{ oracle_asm_disk_string }}{{ item.1.device }}';"|sqlplus -s / as sysasm
  loop: "{{ asm_diskgroups | subelements('disk') }}"
  environment: "{{ oracle_env }}"
  register: status

- name: Print Results
  ansible.builtin.debug: 
   msg: "{{ item.stdout_lines }}"
  with_items: "{{ status.results }}"
  loop_control: 
   label: "{{ item.item }}"
