- name: Delete database(s)
  shell: "{{ oracle_home_db }}/bin/dbca -deleteDatabase -sourceDB {{ item.oracle_db_name }} -sysDBAUserName sys -sysDBAPassword {{ default_dbpass }} -silent"
  with_items: "{{ oracle_databases }}"
  when: item.state |upper == 'ABSENT'
  tags:
    - oradbdelete
  register: oradbdelete
  ignore_errors: true

- ansible.builtin.debug:
    msg: "{{ item.stdout_lines }}"
  loop: "{{ oradbdelete.results }}"
#  loop_control:
#    label: "{{ item.oracle_db_name }}"


  #- ansible.builtin.debug:
  #      msg: "{{ oradbdelete }}"

#- ansible.builtin.debug: 
#    msg: "{{ item }}"
#  loop: "{{ oradbdelete.results | map(attribute='stdout_lines') }}"
