---
# defaults file for dataguard_precheck

scripts_dir: ["{{ work_dir }}", "scripts"]
done_dir: ["{{ work_dir }}", "done"]

prenfsconfig:
 lpp_src:
    # !!! update !!!
  subdir: ''


ignore_precheck: false
