- name: Create Job
  oracle_job:
    hostname: "{{ hostname }}"
    service_name: "{{ service_name }}"
    user: "{{ db_user }}"
    port: "{{ listener_port }}"
    password: "{{ db_password_cdb }}"
    mode: "{{ db_mode }}"
    state: "{{ state }}"
    enabled: "{{ enabled }}"
    job_name: "{{ job_name }}"
    job_action: "{{ job_action }}"
    job_type: "{{ job_type }}"
    repeat_interval: "{{ repeat_interval }}"
  environment: "{{ oracle_env }}"
  register: job
