swapsize: 16384
maxuserproc: 16384
temp_dir: /tmp/podba_gi_temp
response_file_crs_swonly: grid_install.rsp
response_file_upgrade: grid_upgrade.rsp
env_type: GI
apply_ru: True  

directories:
  - /tmp/podba_db_upgrade
  - /tmp/podba_gi_temp
  - /tmp/podba_install_temp