- oracle_sql:
    username: "{{ user }}"
    password: "{{ default_dbpass }}"
    service_name: "{{ service_name }}"
    hostname: "{{ hostname }}"
    port: "{{ listener_port }}"
    mode: "{{ db_mode }}"
    script: "{{ item.script }}"
  with_items:
    - "{{ sqlfile }}"
  environment: "{{ oracle_env }}"
  register: output

- set_fact:
   sql_ouput: |-
        [
        {% for rp in output.results %}
                "{{ rp.msg }}",
        {% endfor %}
        ]

- name: SQL Output
  debug:
    var: sql_ouput
