# Use this playbook to patch database on Single Instance GI. This playbook uses opatchauto utility.

- name: Apply binary patches
  hosts: all     # AIX lpar hostname defined in Ansible inventory.
  gather_facts: False
  remote_user: oracle   # Oracle RDBMS user on the AIX lpar.
  vars_files:
     - vars/db-si-opatchauto-vars.yml
  roles:
     - {role: oraswdb_manage_patches }
