# Playbook to drop RAC/Non-RAC databases.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- name: Drop a Database
  hosts: all                     # Target Lpar hostname.
  remote_user: oracle                   # Remote username.
  gather_facts: false
  vars_files:
   - vars/delete-db-vars.yml
   - vars/vault.yml  
  roles:
     - { role: oradb_delete }
