# Playbook to patch Single Instance Grid Infrastructure
- name: Apply patches to GI
  hosts: all                     # AIX Lapr hostgroup name defined in Ansible inventory.
  remote_user: oracle                   # Grid Home Owner.
  gather_facts: False
  vars_files:
   - vars/gi-si-opatchauto-vars.yml
  roles:
     - {role: oraswgi_manage_patches }  
