# Playbook to manage pluggable databases.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#

- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-pdb-vars.yml
  roles:
     - { role: oradb_manage_pdb }
