# Playbook to manage database directories.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-directories-vars.yml
  roles:
     - { role: oradb_manage_directories }
