# Playbook to create ACFS on a RAC environment
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.

- name: Create ACFS in RAC
  gather_facts: no
  hosts: all                  # AIX Lpar hostgroup defined in ansible inventory.
  remote_user: oracle             # Grid Home owner.
  vars_files:
   - vars/manage-acfs-rac-vars.yml
  roles:
     - {role: manage_acfs_rac }
