# Playbook to manage DBMS jobs.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-job-vars.yml
  roles:
     - { role: oradb_manage_job }
