# Playbook to manage Automatic Workload Repository retention settings.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-awr-vars.yml
  roles:
     - { role: oradb_manage_awr }
