# Playbook to manage database initialization parameters.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-init-parameters-vars.yml
  roles:
     - { role: oradb_manage_initparams }
