# Playbook to execute adhoc SQL scripts on a database.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-arbitrarysql-vars.yml
  roles:
     - { role: oradb_manage_sql }
