# Playbook to manage redo log groups.
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: localhost
  connection: local
  vars_files:
   - vars/vault.yml
   - vars/manage-redo-vars.yml
  roles:
     - { role: oradb_manage_redo }
