# This playbook is used to upgrade Standalone Grid from 12c to 19c.
# Install 19c RDBMS.
# Upgrades the user listed databases from 12c to 19c.
#
# Before executing this playbook, please refer the documentation inside the collection_dir/docs directory.
#
- hosts: all                            # Provide the name of the target lpar registered in ansible inventory.
  remote_user: root                     # This needs to be run by "root" user.
  gather_facts: False
  vars_files:
      - vars/upgrade/upgrade_si_vars.yml
      - vars/vault.yml
  roles:
     - role: si_has_upgrade
       tags: si_has_upgrade
     - role: oracle_install
       tags: oracle_install
     - role: db_upgrade
