---
galaxy_info:
  role_name: asm_add_disk_aix
  description: Ansible role to add ASM disk
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
  - name: AIX
    versions:
    - all

  galaxy_tags: [aix]
  dependencies: []
